name: CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'     
        required: true
        
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate release + changelog
        id: relnotes
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          newTag: ${{ github.event.inputs.tag }}
          generateArtifact: true
        
      - name: Test the generated release notes
        run: echo "${{ steps.relnotes.outputs.relnotes }}"
        
      - uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.txt

